name: Node.js CI

on:  
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: 'Deploy to DO'
      uses: appleboy/ssh-action@master
      with:
        host: 164.90.149.116
        username: root
        key: ${{ secrets.km1.pub }}
        script: 'cd /root && git pull && npm install && pm2 restart all'
